AspNet_MVC_SPU111/Controllers/CartController.cs
using AspNet_MVC_SPU111.Helpers;
using DataAccess.Data;
using DataAccess.Data.Entities;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace AspNet_MVC_SPU111.Controllers
{
    public class CartController : Controller
    {
        private readonly ShopSPUDbContext ctx;

        public CartController(ShopSPUDbContext ctx)
        {
            this.ctx = ctx;
        }
        public IActionResult Index()
        {
            List<int>? ids = HttpContext.Session.Get<List<int>>("cart_items");

            List<Product> products = new();

            if (ids != null)
                products = ctx.Products.Where(x => ids.Contains(x.Id)).ToList();

            return View(products);
        }

        public IActionResult Add(int id)
        {
            List<int>? ids = HttpContext.Session.Get<List<int>>("cart_items");

            if (ids == null)
                ids = new List<int>();

            ids.Add(id);

            HttpContext.Session.Set("cart_items", ids);

            return RedirectToAction("Index", "Home");
        }
    }
}

AspNet_MVC_SPU111/Controllers/OrdersController.cs
using AspNet_MVC_SPU111.Helpers;
using DataAccess.Data;
using DataAccess.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AspNet_MVC_SPU111.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly ShopSPUDbContext ctx;

        private string CurrentUserId => User.FindFirstValue(ClaimTypes.NameIdentifier);

        public OrdersController(ShopSPUDbContext ctx)
        {
            this.ctx = ctx;
        }

        public IActionResult Index()
        {
            var items = ctx.Orders.Where(x => x.UserId == CurrentUserId).ToList();

            return View(items);
        }

        public IActionResult Create()
        {
            List<int>? ids = HttpContext.Session.Get<List<int>>("cart_items");

            List<Product> products = new();

            if (ids != null)
                products = ctx.Products.Where(x => ids.Contains(x.Id)).ToList();

            var order = new Order()
            {
                Date = DateTime.Now,
                UserId = CurrentUserId,
                Products = products,
                TotalPrice = products.Sum(x => x.Price)
            };

            ctx.Orders.Add(order);
            ctx.SaveChanges();
            
            // clear cart items
            HttpContext.Session.Remove("cart_items");

            return RedirectToAction("Index");
        }
    }
}

AspNet_MVC_SPU111/Controllers/ProductsController.cs
using AspNet_MVC_SPU111.Helpers;
using AspNet_MVC_SPU111.Models;
using DataAccess.Data;
using DataAccess.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AspNet_MVC_SPU111.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductsController : Controller
    {
        private readonly ShopSPUDbContext ctx;
        private readonly IFileService fileService;

        public ProductsController(ShopSPUDbContext ctx, IFileService fileService)
        {
            this.ctx = ctx;
            this.fileService = fileService;
        }

        private void LoadCategories()
        {
            this.ViewBag.Categories = new SelectList(ctx.Categories.ToList(), "Id", "Name");
        }

        // Get all products
        [AllowAnonymous]
        public IActionResult Index()
        {
            var products = ctx.Products.ToList();

            return View(products);
        }

        // GET: show create form page
        [HttpGet]
        public IActionResult Create()
        {
            // Ways of sending data to View
            // 1 - use View.Model: return View(obj)
            // 2 - use View.TempData: this.TempDate["Property"] = value
            // 3 - use View.ViewBag: this.ViewBag.Property = value
            //this.ViewBag.Categories = new SelectList(ctx.Categories.ToList(), "Id", "Name");
            LoadCategories();

            return View();
        }

        // POST: add product to the database
        [HttpPost]
        public async Task <IActionResult> Create(CreateProductModel model)
        {
            // validate all Product properties
            if (!ModelState.IsValid)
            {
                LoadCategories();
                return View(model);
            }

            var product = new Product()
            {
                Name = model.Name,
                CategoryId = model.CategoryId,
                Description = model.Description,
                Discount = model.Discount,
                InStock = model.InStock,
                Price = model.Price,
                ImageUrl = await fileService.SaveProductImage(model.ImageFile) // save image to the server
            };

            ctx.Products.Add(product);
            ctx.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var item = ctx.Products.Find(id);

            if (item == null) return NotFound();

            LoadCategories();

            return View(item);
        }

        // POST: update product in the database
        [HttpPost]
        public IActionResult Edit(Product product)
        {
            // validate all Product properties
            if (!ModelState.IsValid)
            {
                LoadCategories();
                return View(product);
            }

            ctx.Products.Update(product);
            ctx.SaveChanges();

            return RedirectToAction("Index");
        }


        // Delete product by ID
        public IActionResult Delete(int id)
        {
            var item = ctx.Products.Find(id);

            if (item == null) return NotFound();

            ctx.Products.Remove(item);
            ctx.SaveChanges(); // delete from db

            return RedirectToAction("Index");
        }
    }
}

AspNet_MVC_SPU111/Views/Shared/_Layout.cshtml
@using DataAccess.Data.Entities;
@using Microsoft.AspNetCore.Identity;

@inject SignInManager<User> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNet_MVC_SPU111</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AspNet_MVC_SPU111.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">My Shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="About">About</a>
                        </li>

                        @if (User.IsInRole(Roles.Admin.ToString()))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Products" asp-action="Index">Products</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Cart" asp-action="Index">Cart</a>
                        </li>

                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Orders" asp-action="Index">Orders</a>
                            </li>
                        }
                    </ul>

                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ASP.NET MVC Educational Project | SPU111 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>